### ISSUE TITLE
[QUESTION] How to do something when the value of a property changes?

### ISSUE THREAD

**Issue by ComptonAlvaro** [CommunityToolkit/MVVM-Samples#121]
I would like to do something when a bool property changes the value when in the view the user chages the value.

I have this:

```
[ObservableProperty]
bool _myProperty;
```

In somewhere, I don't remember where, I have read I could define a method which name is On[PropertyName] or On[PropertyName]Changed or somethink like that, that would be execute when the value of the property changes.

I have probe some variations of this, but all of them fail.

I am wrong and I misunderstood the examples that I have read?

 Thanks.

**Comment by Sergio0694** [comment]
There's several options, depending on what you need. You can find docs and more examples [on MS Learn](https://learn.microsoft.com/en-us/dotnet/communitytoolkit/mvvm/generators/observableproperty#running-code-upon-changes) 🙂

**Comment by ComptonAlvaro** [comment]
Thanks, it was I am looking for.
