### ISSUE TITLE
Can't execute samples due to missing .md files and code not working on Win 10

### ISSUE THREAD

**Issue by fplagamba** [CommunityToolkit/MVVM-Samples#125]
Hi Community,
I am new to MVVM Toolkit so I downloaded the examples 
but I found two problems:

# 1
Several .md files are missing

# 2
It seems it's not possible to run the code on Win 10 and this is a big problem for me 
because I can't upgrade my system to Win 11

![20230703_224052](https://github.com/CommunityToolkit/MVVM-Samples/assets/138527879/f925f834-fc2d-49fd-af69-16decffb2fbe)

**Comment by Sergio0694** [comment]
This sample app uses a git submodule, have you cloned the repo recursively?
You'll need:

```cmd
git clone --recurse-submodules <REPO_LINK>
```

If you've already cloned, you can update with:

```cmd
git submodule update --init --recursive
```

As for Windows 11, the sample app doesn't require it at all. Let us know if updating solved the issue for you! 🙂

**Comment by fplagamba** [comment]
Hi Sergio,
I reloaded the sample application and now everything works perfectly.
Thanks for the quick fix :-)
I wish you a good day!
