### ISSUE TITLE
Update property when another changes

### ISSUE THREAD

**Issue by MattePozzy** [CommunityToolkit/MVVM-Samples#132]
Hi,
in a old XF application I have some properties declare like this one:
`public bool SpeseWOButtonVisible { get { return SpeseWOVisible || BtutteSezioniChiuse; } }
`
How can I bring them into .MAUI and turn them into an `ObservableProperty`?

I used this code

```
public bool SpeseWOButtonVisible { get { return SpeseWOVisible || BtutteSezioniChiuse; } }
[ObservableProperty]
private bool _speseWOVisible;
private bool BtutteSezioniChiuse = true;
```

but when I update from the ViewModel `SpeseWOVisible` or `BtutteSezioniChiuse`, `SpeseWOButtonVisible` is not updated and consequently the UI does not update as well.

How can I solve this?

Thank you.

**Comment by DaveInCaz** [comment]
Have you looked at https://learn.microsoft.com/en-us/dotnet/communitytoolkit/mvvm/generators/observableproperty#notifying-dependent-properties ?

**Comment by MattePozzy** [comment]
> Have you looked at https://learn.microsoft.com/en-us/dotnet/communitytoolkit/mvvm/generators/observableproperty#notifying-dependent-properties ?
> 
> I think it is meant for situations like this.


Hi @DaveInCaz, thank you for your reply but unfortunately I have already looked at that link but could not apply it to my case.
I tried using `NotifyPropertyChangedFor` but it still doesn't update the UI.

**Comment by Olaf-R** [comment]
I'm not sure as to whether I oversee the obvious or misunderstand the problem, but here's two ways to react to changes to an Observable property in the MVVM toolkit:

- use/add [NotifyPropertyChangedFor(nameof(YourOtherProperty))] in the original property
- react to a change in your original property by overriding i.e. the Changed-handler, for instance (for a bool prop): partial void OnYourOriginalPropertyChanged(bool value)

`
    [ObservableProperty]
    [NotifyPropertyChangedFor(nameof(OtherProperty))]
    private bool originalProperty;

    partial void OnOriginalPropertyChanged(bool value)
    {
        // do something ...
    }
`
