### ISSUE TITLE
Will the project be updated?

### ISSUE THREAD

**Issue by DominikErnst** [CommunityToolkit/MVVM-Samples#133]
Are there no improvements, adjustments or corrections? The last changes are 2 years old. 

Which alternative should I use?

**Comment by Sergio0694** [comment]
This is just a sample app 🙂

We'll update it when we add new features in the MVVM Toolkit, but it's lower priority. [The docs on MS Learn](https://learn.microsoft.com/en-us/dotnet/communitytoolkit/mvvm/) are always up to date, so you can also just use those as a reference. As for the MVVM Toolkit, that's still fully supported and with new features planned, of course.
