### ISSUE TITLE
How can I trigger validation when generating properties using the ObservableProperty attribute?

### ISSUE THREAD

**Issue by yangf85** [CommunityToolkit/MVVM-Samples#144]
Hello everyone, 
I'm currently facing a challenge.
 When using ObservableProperty, validation isn't triggered, and I have to use the full notification property. 
Is there a way to trigger validation while using ObservableProperty?

![Image](https://github.com/user-attachments/assets/8d7e1955-7d5f-4242-ac7d-f6b4875fa065)

**Comment by Sergio0694** [comment]
You can do this by adding `[NotifyDataErrorInfo]` on the observable property 🙂

**Comment by yangf85** [comment]
> You can do this by adding `[NotifyDataErrorInfo]` on the observable property 🙂

thanks, i will try it.

**Comment by yangf85** [comment]
> You can do this by adding `[NotifyDataErrorInfo]` on the observable property 🙂

Hi.
I tried using the NotifyDataErrorInfo attribute, but found that it still doesn't work. Could there be an issue with the way I'm using it?
this is a view.
![Image](https://github.com/user-attachments/assets/ff6312f3-0d41-4275-ac81-06a37a52fead)
this is a viewmodwl
![Image](https://github.com/user-attachments/assets/291fc669-2f90-445e-9017-ebc3e51f035f)

![Image](https://github.com/user-attachments/assets/734544ef-f93f-420e-9cfe-b0f71d7b4ca4)
