### ISSUE TITLE
Unable to build Samples

### ISSUE THREAD

**Issue by LadderLogic** [CommunityToolkit/MVVM-Samples#48]
`Error occurred while restoring NuGet packages: Unable to load the service index for source https://pkgs.dev.azure.com/dotnet/WindowsCommunityToolkit/_packaging/WindowsCommunityToolkit-MainLatest/nuget/v3/index.json
`

While attempting to build the UWP project, a notification to login to my microsoftt account pop-ups repeatedly and eventually fails with this error message. It appears that the packagemanager is referring to a CI package manager that I don't have access to. Please advice.

**Comment by Sergio0694** [comment]
I think this might be a consequence of the org rename to `CommunityToolkit`.
FYI @michael-hawker we should double check and make sure this repo is updated as well 😄

Thanks @LadderLogic for the report!

**Comment by michael-hawker** [comment]
Yup, sorry this was from our org name change which modified the URL for the feed. I've updated it in the repo.

If you're using our preview feed as well, I've updated the Preview Packages [Wiki](https://aka.ms/wct/wiki)

**Comment by LadderLogic** [comment]
Tested working with the changes. Thank you.
