### ISSUE TITLE
MAUI Sample

### ISSUE THREAD

**Issue by michael-hawker** [CommunityToolkit/MVVM-Samples#49]
We should copy the XF sample and make a MAUI sample as well.

FYI @brminnick

**Comment by brminnick** [comment]
Right on! I'm happy to do it! 

Feel free to assign it to me 👍

**Comment by Sergio0694** [comment]
Awesome! I've assigned the issue to you @brminnick! 🚀
I've switched the backend to use `CommunityToolkit.Mvvm` in #44, so depending on when you start looking at this (either before or after that's merged), you might want to branch off of that so that you'll already be setup with the right final package 😄

**Comment by michael-hawker** [comment]
FYI @brminnick I merged #44 and tested its Xamarin Forms sample; so you should be good to branch off of main now and copy the XF to transform into a Maui sample!

**Comment by cairoutm** [comment]
Hi;

First of all, thank you for this awesome toolkit. 
FYI,  I couldn't find the sample for MAUI project in the repository. Only Xamarin form sample is available.  Thanks

**Comment by michael-hawker** [comment]
@cairoutm there isn't a MAUI version of the sample app yet, that's what this issue is tracking.

@jamesmontemagno did some videos and has a [repo here](https://github.com/jamesmontemagno/MVVMSourceGenerators/tree/master/dotnet-maui) which shows an example, which should show you how to get started with any MAUI integration.

**Comment by RomanBlyshchyk** [comment]
It's been more than 3 years... Hope it gets resolved at some point. It would be great to have a detailed Maui project, as Xamarin is now deprecated. 🙏

**Comment by brminnick** [comment]
Whoops - that's on me. I've opened up a pR for it here: https://github.com/CommunityToolkit/MVVM-Samples/issues/49#issuecomment-2405597958

We have samples in the CommunityToolkit MAUI repos. We take a lot of pride to ensure our sample apps follow best practices:
- [`CommiunityToolkit.Maui` Sample]( https://github.com/CommunityToolkit/Maui/tree/main/samples
- [`CommiunityToolkit.Maui.Markup` Sample]( https://github.com/CommunityToolkit/Maui.Markup/tree/main/samples
